# Generated by Django 4.2.4 on 2023-12-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffTypesMaster',
            fields=[
                ('STid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Tname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='staffMaster',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('hiredDate', models.DateField()),
                ('pic', models.FileField(upload_to='staffProfileImg')),
                ('DOB', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.stafftypesmaster')),
            ],
        ),
    ]
