# Generated by Django 4.2.4 on 2023-12-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('MenuId', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=255)),
                ('sub_menu_id', models.IntegerField()),
            ],
        ),
    ]
