# Generated by Django 4.2.4 on 2024-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_menumaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmaster',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
