# Generated by Django 4.2.4 on 2024-01-02 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccancyMaster',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vaccancyName', models.CharField(max_length=250)),
                ('vaccancyInfo', models.TextField()),
                ('postedDate', models.DateField(auto_now_add=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMaster',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=255)),
                ('cresume', models.FileField(upload_to='CandidateResume')),
                ('applydate', models.DateField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vaccancymaster')),
            ],
        ),
    ]
