# Generated by Django 3.1.12 on 2024-12-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vaccancymaster_vpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccancymaster',
            name='vpic',
            field=models.ImageField(blank=True, null=True, upload_to='vaccancy_pictures'),
        ),
    ]
